#pragma once

#define VULKAN_CPU_ALLOCATOR nullptr

#define VULKAN_REUSE_FENCES 1

#ifndef VULKAN_USE_DIFFERENT_POOL_CMDBUFFERS
#define VULKAN_USE_DIFFERENT_POOL_CMDBUFFERS 1
#endif

#ifndef VULKAN_USE_IMAGE_ACQUIRE_FENCES
#define VULKAN_USE_IMAGE_ACQUIRE_FENCES 1
#endif

#ifndef VULKAN_DELETE_STALE_CMDBUFFERS
#define VULKAN_DELETE_STALE_CMDBUFFERS 1
#endif

#define VULKAN_SUPPORTS_ASTC_DECODE_MODE 0

#define VULKAN_ENABLE_AGGRESSIVE_STATS 0